//
//  GameMainInteractor.swift
//  O_FOR_IOS
//
//  Created khanathip rachprachon on 19/3/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GameMainInteractor: GameMainInteractorProtocol {

    weak var presenter: GameMainPresenterProtocol?
}
