//
//  GameMainPresenter.swift
//  O_FOR_IOS
//
//  Created khanathip rachprachon on 19/3/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class GameMainPresenter: GameMainPresenterProtocol {

    weak private var view: GameMainViewProtocol?
    var interactor: GameMainInteractorProtocol?
    private let router: GameMainWireframeProtocol

    init(interface: GameMainViewProtocol, interactor: GameMainInteractorProtocol?, router: GameMainWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
