//
//  GameMainProtocols.swift
//  O_FOR_IOS
//
//  Created khanathip rachprachon on 19/3/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol GameMainWireframeProtocol: class {

}
//MARK: Presenter -
protocol GameMainPresenterProtocol: class {

}

//MARK: Interactor -
protocol GameMainInteractorProtocol: class {

  var presenter: GameMainPresenterProtocol?  { get set }
}

//MARK: View -
protocol GameMainViewProtocol: class {

  var presenter: GameMainPresenterProtocol?  { get set }
}
